export const FETCH_TESTS_REQUEST = 'tests/FETCH_TESTS_REQUEST';
export const FETCH_TESTS_SUCCESS = 'tests/FETCH_TESTS_SUCCESS';
export const FETCH_TESTS_FAILURE = 'tests/FETCH_TESTS_FAILURE';

export const FETCH_TEST_REQUEST = 'tests/FETCH_TEST_REQUEST';
export const FETCH_TEST_SUCCESS = 'tests/FETCH_TEST_SUCCESS';
export const FETCH_TEST_FAILURE = 'tests/FETCH_TEST_FAILURE';

export const CREATE_TEST_REQUEST = 'tests/CREATE_TEST_REQUEST';
export const CREATE_TEST_SUCCESS = 'tests/CREATE_TEST_SUCCESS';
export const CREATE_TEST_FAILURE = 'tests/CREATE_TEST_FAILURE';

export const UPDATE_TEST_REQUEST = 'tests/UPDATE_TEST_REQUEST';
export const UPDATE_TEST_SUCCESS = 'tests/UPDATE_TEST_SUCCESS';
export const UPDATE_TEST_FAILURE = 'tests/UPDATE_TEST_FAILURE';

export const DELETE_TEST_REQUEST = 'tests/DELETE_TEST_REQUEST';
export const DELETE_TEST_SUCCESS = 'tests/DELETE_TEST_SUCCESS';
export const DELETE_TEST_FAILURE = 'tests/DELETE_TEST_FAILURE';

export const FETCH_SUBJECTS_REQUEST = 'tests/FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_SUCCESS = 'tests/FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILURE = 'tests/FETCH_SUBJECTS_FAILURE';

export const FETCH_TOPICS_REQUEST = 'tests/FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'tests/FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'tests/FETCH_TOPICS_FAILURE';

export const FETCH_SUBTOPICS_REQUEST = 'tests/FETCH_SUBTOPICS_REQUEST';
export const FETCH_SUBTOPICS_SUCCESS = 'tests/FETCH_SUBTOPICS_SUCCESS';
export const FETCH_SUBTOPICS_FAILURE = 'tests/FETCH_SUBTOPICS_FAILURE';
