export const CREATE_QUESTIONS_REQUEST = 'questions/CREATE_QUESTIONS_REQUEST';
export const CREATE_QUESTIONS_SUCCESS = 'questions/CREATE_QUESTIONS_SUCCESS';
export const CREATE_QUESTIONS_FAILURE = 'questions/CREATE_QUESTIONS_FAILURE';

export const FETCH_QUESTIONS_BULK_REQUEST = 'questions/FETCH_QUESTIONS_BULK_REQUEST';
export const FETCH_QUESTIONS_BULK_SUCCESS = 'questions/FETCH_QUESTIONS_BULK_SUCCESS';
export const FETCH_QUESTIONS_BULK_FAILURE = 'questions/FETCH_QUESTIONS_BULK_FAILURE';
